# Numpy
* It is a open source python library that is used in mathematical, scientific, engineering, data science programming.
* Numpy stand for "Numerical Python"
* It works for multidimensional array and matices
* Tensorflow and sickit learn used numpyt at the backend to compute the matrix multiplication
* Since, Numpy it memory effieciency it can easily handle large amount of data more accessible than any other liraries.

# install numpy 

pip install -c anaconda numpy

pip install numpy

In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [3]:
import numpy as np
print(np.__version__)

1.26.4


In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [6]:
arr = np.array([2,4,6,8])

In [7]:
print(arr)

[2 4 6 8]


In [8]:
print(type(arr))

<class 'numpy.ndarray'>


# ndarray is the object of numpy array

In [9]:
arr = np.array((1,2,3,4))

In [10]:
print(arr)

[1 2 3 4]


In [12]:
arr= np.array([1,2,3,4,5,6,7,8,9])

In [13]:
arr+10

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
arr*10

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
arr-10

array([-9, -8, -7, -6, -5, -4, -3, -2, -1])

In [16]:
arr/10

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [17]:
arr = np.array([1,2,3,4,5,6,7,8])
arr.shape

(8,)

In [18]:
arr.dtype

dtype('int32')

In [22]:
arr = np.array([1.1,2.2,3.3,4.4])
arr.dtype

dtype('float64')

# 0-D array

In [23]:
arr = np.array(10)

arr

array(10)

In [24]:
arr.dtype

dtype('int32')

# 1-D array

In [25]:
arr= ((1,2,3,4,5))

ar = np.array(arr)

ar

array([1, 2, 3, 4, 5])

# 2-D array

In [33]:
arr = np.array(([1,2,3],[4,5,6]))


In [34]:
arr.shape

(2, 3)

In [37]:
arr = np.array([(1,2,3), (4,5,6)])

In [38]:
arr.shape

(2, 3)

# 3-D array

In [39]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
arr.shape

(3, 3)

# checking dimension

In [41]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [42]:
a.ndim

0

In [43]:
b.ndim

1

In [44]:
c.ndim

2

In [45]:
d.ndim

3

# indexing array

In [46]:
arr = np.array([1,2,3,4,5])

In [47]:
arr[1]

2

In [48]:
arr[3]

4

In [50]:
sum = arr[1] + arr[3]   # 2+ 4 = 5

sum

6

# 2 -D array

In [51]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [52]:
arr[1,2]

8

In [53]:
arr[0,-1]

5

# 3-D array

In [54]:
arr = np.array([[1,2,3],
                [4,5,6],
                [8,9,10]
                ])

arr[0]

array([1, 2, 3])

In [55]:
arr[0][1]

2

In [56]:
arr[0,1]

2

In [57]:
arr[1,2]

6

In [58]:
arr[0,1,2]

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [59]:
arr = np.array([[[1,2,3],
                [4,5,6],
                [8,9,10]
                ]])

In [60]:
arr[0,1,2]


6