In [1]:
!pip install scipy

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/60.4 kB ? eta -:--:--
     ------------ ------------------------- 20.5/60.4 kB 330.3 kB/s eta 0:00:01
     -------------------------------- ----- 51.2/60.4 kB 435.7 kB/s eta 0:00:01
     -------------------------------------- 60.4/60.4 kB 460.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/46.2 MB ? eta -:--:--
   ---------------------------------------- 0.1/46.2 MB 1.7 MB/s eta 0:00:28
   ---------------------------------------- 0.2/46.2 MB 2.1 MB/s eta 0:00:22
   ---------------------------------------- 0.4/46.2 MB 3.1 MB/s eta 0:00:15
   ---------------------------------------- 0.5/46.2 MB 3.1 MB/s eta 0:00:15
    --------------------------------------- 1.0/46.2 MB 4.4 MB/s eta 0:00:11
   - -------------------------------------- 1.9/46.2 MB 6.6 MB/s eta 0:00:07
   -- ------------------------------------- 2.4/46.2 MB 7.4 MB/s eta 0:00:06
 

In [6]:
import numpy as np

In [2]:
import scipy as sc

In [3]:
print(sc.__version__)

1.12.0


In [8]:
import scipy.linalg as slin

In [7]:
a = np.array([[ 3, -5, 8],

[-1, 2, 3],

[-5, -6, 2]])

# determination

In [9]:
slin.det(a)

259.0

# trace

In [10]:
np.trace(a)

7

# inverse

In [11]:
slin.inv(a)

array([[ 0.08494208, -0.14671815, -0.11969112],
       [-0.05019305,  0.17760618, -0.06563707],
       [ 0.06177606,  0.16602317,  0.003861  ]])

# transpose

In [12]:
np.transpose(a)

array([[ 3, -1, -5],
       [-5,  2, -6],
       [ 8,  3,  2]])

In [13]:
a=np.matrix([[ 3, -5, 8],

[-1, 2, 3],

[-5, -6, 2]])

b=np.matrix([[ 3],

[ 4],

[-1]])

In [14]:
a * b

matrix([[-19],
        [  2],
        [-41]])