In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.26.4


In [3]:
arr = np.zeros((3,3))

arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
arr = np.ones((2,2))

arr

array([[1., 1.],
       [1., 1.]])

In [5]:
arr = np.ones((2,4))

arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# reshape and flatten

In [6]:
arr = np.array([(1,2,3), (4,5,6)])

arr

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [13]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [14]:
arr = np.array([(1,2,3), (4,5,6)])

In [17]:
arr.flatten()

array([1, 2, 3, 4, 5, 6])

In [18]:
arr.ravel()

array([1, 2, 3, 4, 5, 6])

In [22]:
arr.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [25]:
arr.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [28]:
np.ndarray.flatten(arr, order="C")

array([1, 2, 3, 4, 5, 6])

# hstack and vstack

In [29]:
a = np.array([1,2,3])

b = np.array([4,5,6])

In [42]:
np.hstack((a,b), dtype=None)

array([1, 2, 3, 4, 5, 6])

In [39]:
np.hstack((a,b), dtype="a")

array([b'1', b'2', b'3', b'4', b'5', b'6'], dtype='|S11')

In [50]:
a = np.array([1,2,3])

b = np.array([4,5,6])

In [53]:
np.vstack((a,b), casting='same_kind')

array([[1, 2, 3],
       [4, 5, 6]])

# generate random number 

In [54]:
from numpy import random

In [58]:
arr = np.random.rand(3)

In [59]:
arr

array([0.68711296, 0.77062572, 0.14030656])

In [60]:
np.random.rand(2,2)

array([[0.59146909, 0.85938752],
       [0.74773642, 0.58985992]])

In [72]:
np.random.randint(0,2 ,size=[2,2])

array([[0, 1],
       [1, 0]])

In [76]:
np.random.random(size=[1,2])

array([[0.5625617 , 0.31656145]])

# choice

In [81]:
np.random.choice([1,2,3,4,5], size= [2,2])

array([[1, 4],
       [4, 4]])

In [82]:
np.random.choice(['a','e','i','o','u'], size =[2,2])

array([['i', 'e'],
       ['u', 'o']], dtype='<U1')

In [85]:
np.random.choice(['a','e','i','o','u'], size =[1,6])

array([['o', 'u', 'i', 'e', 'a', 'e']], dtype='<U1')

In [105]:
arr = np.random.choice(['a','e','i','o','u'], size =[1,6], p=[0.4,0.1,0.1,0.3,0.1])

In [109]:
arr

array([['o', 'e', 'a', 'o', 'a', 'e']], dtype='<U1')

In [118]:
''.join(np.random.choice(['a','e','i','o','u'], size = 6, p =[0.4,0.1,0.1,0.3,0.1]))

'aiuaaa'